### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by chasemc** [jason-c-kwan/chtc_recipes#1]
This repo popped up in my GitHub feed and I had a quick question, if CHTC supports it, why not use  docker images? Especially for antismash as I think they maintain images?

**Comment by jason-c-kwan** [comment]
CHTC doesn't natively use Docker, it actually emulates docker using Singularity. It is kind of a pain to use - there are lots of errors that can happen silently. Or rather, it tends to work for one instance, and then when you try to do a big parallel run, it chokes. That is why for example the antismash recipe concentrates on building a native environment. It allows running several hundred instances in parallel, no problem.
